-- DCS-CheckrideEnricher.lua  (generated — do not edit by hand)
-- Generated by: node dev/tools/buildReferenceData.js generate
-- Candidates:   689
--
-- USAGE:
--   1. Copy this file to:
--        <Saved Games>\DCS\Scripts\Hooks\DCS-CheckrideEnricher.lua
--   2. Stop the Checkride app (this hook replaces its callbacks).
--   3. Restart DCS, then load any mission (needed for airdrome data).
--   4. Output is written to:
--        <Saved Games>\DCS\checkride-enrichment.json
--   5. Back on the host machine, run:
--        node dev/tools/buildReferenceData.js process
--   6. Remove this hook file and restart DCS to restore normal operation.
--
-- Unit/weapon enrichment runs at simulation start (no mission needed).
-- Airdrome enumeration runs on mission load.  If you only need units/weapons,
-- the partial output written at sim-start is sufficient.

local lfs = require('lfs')
local log = require('log')

local function enrichLog(msg)
    log.write('CheckrideEnricher', log.INFO, tostring(msg))
end

-- ====================================================================
-- JSON encoder (mirrors DCS-CheckrideMission.lua style)
-- ====================================================================
local function jsonEscape(str)
    str = tostring(str)
    str = str:gsub('\\', '\\\\')
    str = str:gsub('"',  '\\"')
    str = str:gsub('\n', '\\n')
    str = str:gsub('\r', '\\r')
    str = str:gsub('\t', '\\t')
    return str
end

local function isSeqTable(t)
    if type(t) ~= 'table' then return false end
    local n = 0
    for k in pairs(t) do
        if type(k) ~= 'number' then return false end
        n = n + 1
    end
    for i = 1, n do if t[i] == nil then return false end end
    return true
end

local function encodeJson(val, depth)
    depth = depth or 0
    if depth > 20 then return '"<depth_limit>"' end
    local t = type(val)
    if t == 'nil'     then return 'null' end
    if t == 'boolean' then return tostring(val) end
    if t == 'number'  then
        if val ~= val or val >= math.huge or val <= -math.huge then return 'null' end
        return tostring(val)
    end
    if t == 'string' then return '"' .. jsonEscape(val) .. '"' end
    if t == 'table' then
        if isSeqTable(val) then
            local parts = {}
            for i, v in ipairs(val) do parts[i] = encodeJson(v, depth + 1) end
            return '[' .. table.concat(parts, ',') .. ']'
        end
        local parts = {}
        for k, v in pairs(val) do
            if type(k) == 'string' then
                table.insert(parts, '"' .. jsonEscape(k) .. '":' .. encodeJson(v, depth + 1))
            end
        end
        return '{' .. table.concat(parts, ',') .. '}'
    end
    return 'null'
end

-- ====================================================================
-- Candidates (auto-generated — 689 total)
-- ====================================================================
local CANDIDATES = {
  "2S6 Tunguska",
  "3BM59_125_AP",
  "53-UBR-281U",
  "53-UOR-281U",
  "55G6 EWR",
  "57E6",
  "7_92x57_Smkl",
  "7_92x57sS",
  "9M311",
  "9M330",
  "9M338K",
  "9M39 Igla",
  "9M723",
  "9M723_HE",
  "A-10A",
  "A-10C",
  "A-10C_2",
  "A-50",
  "AA8",
  "ADM_141A",
  "ADM_141B",
  "AGM-114K",
  "AGM-114L",
  "AGM-154A",
  "AGM-154A - JSOW CEB (CBU-type)",
  "AGM-154B",
  "AGM-154B - JSOW Anti-Armour",
  "AGM-154C",
  "AGM-154C - JSOW Unitary BROACH",
  "AGM-84D",
  "AGM-84H",
  "AGM-86C",
  "AGM-86D",
  "AGM_114",
  "AGM_114K",
  "AGM_12A",
  "AGM_12B",
  "AGM_12C_ED",
  "AGM_130",
  "AGM_130C_9",
  "AGM_154A",
  "AGM_154B",
  "AGM_45A",
  "AGM_45B",
  "AGM_62",
  "AGM_62_I",
  "AGM_65A",
  "AGM_65B",
  "AGM_65D",
  "AGM_65E",
  "AGM_65F",
  "AGM_65G",
  "AGM_65H",
  "AGM_65K",
  "AGM_65L",
  "AGM_78A",
  "AGM_78B",
  "AGM_84D",
  "AGM_84H",
  "AGM_86",
  "AGM_86C",
  "AGR_20A",
  "AGR_20_M151_unguided",
  "AGR_20_M282",
  "AGR_20_M282_unguided",
  "AH-1W",
  "AH-64A",
  "AH-64D",
  "AIM-120B",
  "AIM-120C",
  "AIM-7E",
  "AIM-7E-2",
  "AIM-7F",
  "AIM-7MH",
  "AIM-7P",
  "AIM-9E",
  "AIM-9J",
  "AIM-9JULI",
  "AIM-9L",
  "AIM-9P",
  "AIM-9P3",
  "AIM-9P5",
  "AIM_120",
  "AIM_120C",
  "AIM_7",
  "AIM_9",
  "AIM_9X",
  "AK725",
  "AK_725",
  "ALBATROS",
  "ATZ-10",
  "ATZ-5",
  "ATZ-60_Maz",
  "AT_6",
  "An-30M",
  "Armed Ship",
  "Ataka_9M120",
  "Ataka_9M120F",
  "Ataka_9M220",
  "B-1B",
  "B600_drivable",
  "BAP-100",
  "BAT-120",
  "BDK-775",
  "BDU-33",
  "BDU-45",
  "BDU-45B",
  "BDU-50HD",
  "BDU-50LD",
  "BDU-50LGB",
  "BDU_45",
  "BDU_45B",
  "BDU_45LGB",
  "BKF_AO2_5RT",
  "BKF_PTAB2_5KO",
  "BLG-66 AC",
  "BLG-66 EG",
  "BLG66",
  "BLG66_EG",
  "BMD-1",
  "BMP-1",
  "BMP-2",
  "BMP-3",
  "BRDM-2",
  "BRDM-2_malyutka",
  "BR_250",
  "BR_354N",
  "BR_500",
  "BTR-60",
  "BTR-70",
  "BTR-80",
  "BTR-82A",
  "BTR_D",
  "Bedford_MWD",
  "Blitz_36-6700A",
  "Boiler-house A",
  "Boxcartrinity",
  "Br303",
  "Br303_tr",
  "Bunker",
  "C-130",
  "CATM-9M",
  "CATM_65K",
  "CATM_9M",
  "CBU-103",
  "CBU-105",
  "CBU-87",
  "CBU-97",
  "CBU-99",
  "CBU_99",
  "CH-47D",
  "CH47_AFT_M240H",
  "CH47_AFT_M3M",
  "CH47_AFT_M60D",
  "CH47_PORT_M134D",
  "CH47_PORT_M240H",
  "CH47_PORT_M60D",
  "CH47_STBD_M134D",
  "CH47_STBD_M240H",
  "CH47_STBD_M60D",
  "CHAP_9K720_Cluster",
  "CHAP_9K720_HE",
  "CHAP_BMPT",
  "CHAP_FV101",
  "CHAP_FV107",
  "CHAP_IRISTSLM_CP",
  "CHAP_IRISTSLM_LN",
  "CHAP_IRISTSLM_STR",
  "CHAP_M1083",
  "CHAP_M1130",
  "CHAP_M142_ATACMS_M39A1",
  "CHAP_M142_ATACMS_M48",
  "CHAP_M142_GMLRS_M30",
  "CHAP_M142_GMLRS_M31",
  "CHAP_MATV",
  "CHAP_PantsirS1",
  "CHAP_Project22160",
  "CHAP_Project22160_TorM2KM",
  "CHAP_T64BV",
  "CHAP_T84OplotM",
  "CHAP_T90M",
  "CHAP_TOS1A",
  "CHAP_TorM2",
  "CM_802AKG",
  "CVN_71",
  "CVN_72",
  "CVN_73",
  "CVN_75",
  "CV_1143_5",
  "C_24",
  "C_701IR",
  "C_701T",
  "C_802AK",
  "Cafe",
  "CastleClass_01",
  "Chieftain_mk3",
  "Coach a passenger",
  "Coach a platform",
  "Coach a tank blue",
  "Coach a tank yellow",
  "Coach cargo",
  "Coach cargo open",
  "Comms tower M",
  "Container red 3",
  "Container white",
  "CustomArguments",
  "Default",
  "DelayedGatlingTrigger",
  "Durandal",
  "E-3A",
  "EFT_230Gal",
  "ELNYA",
  "ES44AH",
  "Electric locomotive",
  "Essex",
  "F-14A-135-GR",
  "F-14A-135-GR-Early",
  "F-14A-95-GR",
  "F-14B",
  "F-15C",
  "F-15E",
  "F-15ESE",
  "F-16A",
  "F-16C bl.50",
  "F-16C bl.52d",
  "F-16C_50",
  "F-4E-45MC",
  "F-5E-3",
  "FA-18C_hornet",
  "FAB-250-M62",
  "FARP",
  "FARP CP Blindage",
  "FARP Fuel Depot",
  "FARP Tent",
  "FFAR M156 WP",
  "FFAR Mk1 HE",
  "FFAR Mk5 HEAT",
  "FIM-92C Stinger",
  "FIM_92C",
  "FPS-117",
  "FPS-117 Dome",
  "FPS-117 ECS",
  "Farm B",
  "FeedBelt",
  "FireEffect",
  "FlagPoleStatic",
  "Flak18_Sprgr_39",
  "GAR-8",
  "GAZ-66",
  "GB-6",
  "GB-6-HE",
  "GB-6-SFW",
  "GBU-12",
  "GBU-16",
  "GBU-31",
  "GBU-31V",
  "GBU-32",
  "GBU-38",
  "GBU-39",
  "GBU_15_V_1_B",
  "GBU_15_V_31_B",
  "GBU_24",
  "GBU_31",
  "GBU_31_V_2B",
  "GBU_31_V_3B",
  "GBU_31_V_4B",
  "GBU_32_V_2B",
  "GBU_38",
  "GBU_39",
  "GBU_43",
  "GBU_43B",
  "GBU_54_V_1B",
  "GBU_8_B",
  "GPS_Spoofer_Blue",
  "GPS_Spoofer_Red",
  "Grad_FDDM",
  "HB_F-4E_EXT_AGM12A",
  "HB_F-4E_EXT_AGM12B",
  "HB_F-4E_EXT_AGM12C",
  "HB_F-4E_EXT_AGM45",
  "HB_F-4E_EXT_GBU8",
  "HB_F4E_GBU15V1",
  "HEMTT TFFT",
  "HEMTT_C-RAM_Phalanx",
  "HL_B8M1",
  "HL_DSHK",
  "HL_KORD",
  "HL_ZU-23",
  "HOT2",
  "HOT3_MBDA",
  "HY-2",
  "HY_2",
  "HandyWind",
  "HarborTug",
  "Hawk ln",
  "Hawk sr",
  "Hawk tr",
  "HelicopterCarrier",
  "Hummer",
  "IAFS_ComboPak_100",
  "IL-76MD",
  "IL-78M",
  "IRIS-T-SL",
  "Igla_1E",
  "Infantry AK Ins",
  "J-11A",
  "K307_155HE",
  "KAB_1500LG",
  "KAB_1500T",
  "KAB_500S",
  "KC-135",
  "KD_20",
  "KD_63",
  "KD_63B",
  "KH_101",
  "KH_555",
  "KS-19",
  "KS19_100AP",
  "KS19_100HE",
  "Ka-27",
  "Ka-50",
  "Ka-50_3",
  "Kh25MP_PRGS1VP",
  "L118_Unit",
  "L23A1_APFSDS",
  "L31A7_HESH",
  "LARC-V",
  "LAU-10",
  "LAU-10 pod - 4 x 127mm ZUNI, UnGd Rkts Mk71, HE/FRAG",
  "LAU-131_AGR-20_M151",
  "LAU-131_AGR-20_M282",
  "LAU-131_M151",
  "LAU-131_M156",
  "LAU-131_M257",
  "LAU-131_M274",
  "LAU-131_MK1",
  "LAU-131_MK5",
  "LAU-131_MK61",
  "LAU-131_WTU-1/B",
  "LAU-61",
  "LAU-68_M151",
  "LAU-68_M156",
  "LAU-68_M257",
  "LAU-68_M274",
  "LAU-68_MK1",
  "LAU-68_MK5",
  "LAU-68_MK61",
  "LAU-68_WTU-1/B",
  "LAV-25",
  "LS_6",
  "LS_6_100",
  "LS_6_500",
  "LUU_2B",
  "La_Combattante_II",
  "Land_Rover_101_FC",
  "Land_Rover_109_S3",
  "Landmine",
  "Leopard-2",
  "Leopard-2A5",
  "Locomotive",
  "M 818",
  "M-1 Abrams",
  "M-109",
  "M-113",
  "M-2 Bradley",
  "M-60",
  "M1043 HMMWV Armament",
  "M1045 HMMWV TOW",
  "M1097 Avenger",
  "M1126 Stryker ICV",
  "M1128 Stryker MGS",
  "M1134 Stryker ATGM",
  "M1A2C_SEP_V3",
  "M256_120_AP_L55",
  "M256_120_HE_L55",
  "M257_FLARE",
  "M2A1_halftrack",
  "M30",
  "M31",
  "M39A1",
  "M46",
  "M48",
  "M48 Chaparral",
  "M4_Sherman",
  "M6 Linebacker",
  "M61",
  "M978 HEMTT Tanker",
  "MJ-1_drivable",
  "MK-82",
  "MK-82AIR",
  "MK-82Y",
  "MK-82_Snakeye",
  "MK-83",
  "MK-83AIR",
  "MK106",
  "MK76",
  "MOLNIYA",
  "MOSCOW",
  "MTLB",
  "M_134_Turret",
  "Mark_46",
  "MaxxPro_MRAP",
  "Mi-24V",
  "Mi-26",
  "Mi-28N",
  "Mi-8MT",
  "MiG-29A",
  "Military staff",
  "Mistral",
  "Mk_82B",
  "Mk_82BT",
  "Mk_82P",
  "Mk_82PT",
  "Mk_82SB",
  "Mk_82SP",
  "Mk_82Y",
  "Mk_82YT",
  "Mk_83AIR",
  "Mk_83BT",
  "Mk_83CT",
  "Mk_83P",
  "Mk_83PT",
  "Mk_84AIR_GP",
  "Mk_84AIR_TP",
  "Mk_84P",
  "Mk_84T",
  "NASAMS_Command_Post",
  "NASAMS_LN_B",
  "NASAMS_LN_C",
  "NASAMS_Radar_MPQ64F1",
  "NEUSTRASH",
  "OF_350",
  "OH58D",
  "Osa 9A33 ln",
  "P-51D",
  "P-51D-30-NA",
  "P14_SR",
  "P20_drivable",
  "PERRY",
  "PG-16",
  "PG-9",
  "PG_16V",
  "PG_9V",
  "PTB_450",
  "PT_76",
  "P_27P",
  "P_27PE",
  "P_27T",
  "P_27TE",
  "P_60",
  "Paratrooper AKS-74",
  "Paratrooper RPG-16",
  "Pz_IV_H",
  "Pzgr_39/40",
  "R-13M",
  "R-13M1",
  "R-3R",
  "R-3S",
  "R-60",
  "R-60a",
  "R530F EM",
  "R530F IR",
  "RBK_250_275_AO_1SCH",
  "RBK_500U_BETAB_M",
  "RBK_500U_OAB_2_5RT",
  "RD_75",
  "REZKY",
  "RIM_116A",
  "RLS_19J6",
  "ROCKEYE",
  "RPC_5N62V",
  "RQ-1A Predator",
  "R_530F_EM",
  "R_530F_IR",
  "R_550",
  "R_550_M1",
  "Radial",
  "Rapier",
  "Rb 24",
  "Rb 24J",
  "Rb 74",
  "Rb_04",
  "Repair workshop",
  "S-200_Launcher",
  "S-24",
  "S-300PS 40B6M tr",
  "S-300PS 40B6MD sr",
  "S-300PS 40B6MD sr_19J6",
  "S-300PS 54K6 cp",
  "S-300PS 5H63C 30H6_tr",
  "S-300PS 5P85C ln",
  "S-300PS 5P85D ln",
  "S-300PS 64H6E sr",
  "S-60_Type59_Artillery",
  "SA-11 Buk LN 9A310M1",
  "SA-11 Buk SR 9S18M1",
  "SA-18 Igla manpad",
  "SA-18 Igla-S comm",
  "SA-18 Igla-S manpad",
  "SA2V755",
  "SA57E6",
  "SA5V28",
  "SA9M311",
  "SA9M330",
  "SA9M338K",
  "SAB_100MN",
  "SAB_100_FLARE",
  "SAB_250_200",
  "SAB_250_FLARE",
  "SAMP125LD",
  "SAMP250HD",
  "SAMP250LD",
  "SAMP400HD",
  "SAMP400LD",
  "SAU 2-C9",
  "SAU Akatsia",
  "SAU Gvozdika",
  "SAU Msta",
  "SA_IRIS_T_SL",
  "SINGLE_HELIPAD",
  "SNR_75V",
  "SON_9",
  "SPIKE_ER",
  "SPIKE_ER2",
  "SPIKE_ERA",
  "SPRD_99Twin",
  "S_68",
  "S_75M_Volhov",
  "S_75_Rocket",
  "S_75_ZIL",
  "S_8OM_FLARE",
  "Scud_B",
  "Sd_Kfz_251",
  "Sea_Cat",
  "Sea_Dart",
  "Sea_Wolf",
  "Seawise_Giant",
  "Ship_Tilde_Supply",
  "Silkworm_SR",
  "Small house 1A",
  "Small house 2C",
  "Smerch",
  "SmokeEffect",
  "Soldier AK",
  "Soldier M4",
  "Soldier RPG",
  "Soldier stinger",
  "Sprgr_34_L48",
  "Stennis",
  "Stinger comm",
  "Strela-1 9P31",
  "Strela-10M3",
  "Su-17M4",
  "Su-24M",
  "Su-24MR",
  "Su-25",
  "Su-25T",
  "Su-27",
  "Su-33",
  "Su-34",
  "Subsidiary structure 1",
  "Super_530D",
  "Super_530F",
  "T-34-85",
  "T-55",
  "T-72B",
  "T-72B3",
  "T-80B",
  "T-80UD",
  "T-90",
  "T155_Firtina",
  "T62M",
  "TF-51D",
  "TGM_65D",
  "TGM_65G",
  "TGM_65H",
  "TICONDEROG",
  "TZ-22_KrAZ",
  "TakeOffParking",
  "Tankcartrinity",
  "Tech hangar A",
  "Tor 9A331",
  "TugHarlan_drivable",
  "TurboProp",
  "Type_200A",
  "Type_3_80mm_AA",
  "Type_88_75mm_AA",
  "Type_89_I_Go",
  "Type_94_25mm_AA_Truck",
  "Type_94_Truck",
  "Type_96_25mm_AA",
  "Type_98_Ke_Ni",
  "Type_98_So_Da",
  "UAZ-469",
  "UH-1H",
  "USS_Arleigh_Burke_IIa",
  "Ural ATsP-6",
  "Ural-375",
  "Ural-375 PBU",
  "Ural-375 ZU-23",
  "Ural-4320 APA-5D",
  "Ural-4320-31",
  "Ural-4320T",
  "VAB_Mephisto",
  "Vikhr_M",
  "VisualHeatEffect",
  "Vulcan",
  "Wellcarnsc",
  "Workshop A",
  "X-59M",
  "X_101",
  "X_25ML",
  "X_25MP",
  "X_25MR",
  "X_29L",
  "X_29T",
  "X_29TE",
  "X_555",
  "X_59M",
  "YJ-12",
  "YJ-83",
  "YJ-83K",
  "YU-6",
  "ZIL-135",
  "ZSU-23-4 Shilka",
  "ZSU_57_2",
  "ZU-23 Emplacement",
  "ZU-23 Emplacement Closed",
  "ZiL-131 APA-80",
  "aim-9",
  "aim-9E",
  "aim-9J",
  "aim-9JULI",
  "aim-9L",
  "aim-9p",
  "aim-9p5",
  "aim-9x",
  "aim_7",
  "aim_7_E",
  "aim_7_E_2",
  "aim_7_F",
  "aim_7_H",
  "aim_7_P",
  "ao-2_5rt_block2",
  "ara_vdm",
  "atconveyor",
  "bofors40",
  "flak18",
  "gaz-66_civil",
  "generator_5i57",
  "hms_invincible",
  "house1arm",
  "house2arm",
  "hy_launcher",
  "kamaz_tent_civil",
  "leander-gun-achilles",
  "leander-gun-andromeda",
  "leander-gun-ariadne",
  "leander-gun-condell",
  "leander-gun-lynch",
  "leopard-2A4",
  "leopard-2A4_trs",
  "magic-r550",
  "magic-r550_1",
  "outpost_road",
  "prmg_gp_beacon",
  "prmg_loc_beacon",
  "ptab-2_5ko_block2",
  "r-60",
  "r11_volvo_drivable",
  "r_27r",
  "r_27re",
  "r_27t",
  "r_27te",
  "rapier_fsa_blindfire_radar",
  "rapier_fsa_launcher",
  "rapier_fsa_optical_tracker_unit",
  "rsbn_beacon",
  "s-200_5b21_missile",
  "santafe",
  "tacr2a",
  "tt_B8M1",
  "tt_DSHK",
  "tt_KORD",
  "tt_ZU-23",
  "ural_4230_civil_b",
  "ural_4230_civil_t",
  "ural_atz5_civil",
  "zil-131_civil"
}

-- ====================================================================
-- Enum mappings — must stay in sync with DCS-CheckrideMission.lua
-- ====================================================================
local GUIDANCE_NAMES = {
    [0] = 'NONE',
    [4] = 'RADAR_ACTIVE',
    [5] = 'RADAR_SEMI_ACTIVE',
    [6] = 'RADAR_PASSIVE',
    [7] = 'IR',
    [8] = 'LASER',
    [9] = 'TV',
}

local WEAPON_CATEGORY_NAMES = {
    [0] = 'SHELL',
    [1] = 'MISSILE',
    [2] = 'ROCKET',
    [3] = 'BOMB',
    [4] = 'TORPEDO',
}

local MISSILE_CATEGORY_NAMES = {
    [1] = 'AAM',
    [2] = 'SAM',
    [3] = 'BM',
    [4] = 'ANTI_SHIP',
    [5] = 'ARM',
    [6] = 'OTHER',
}

-- Numeric constants so we don't depend on Unit.Category being defined at hook load time
local UNIT_CATEGORY_NAMES = {
    [0] = 'AIRPLANE',
    [1] = 'HELICOPTER',
    [2] = 'GROUND_UNIT',
    [3] = 'SHIP',
    [4] = 'STRUCTURE',
}

local AIRBASE_CATEGORY_NAMES = {
    [0] = 'AIRDROME',
    [1] = 'HELIPAD',
    [2] = 'SHIP',
}

-- ====================================================================
-- Accumulated result
-- ====================================================================
local result = {
    units     = {},
    weapons   = {},
    airdromes = {},
    meta = {
        generatedAt       = os.date('!%Y-%m-%dT%H:%M:%SZ'),
        candidatesScanned = 689,
        theaters          = {},
    },
}

local outputPath = lfs.writedir() .. 'checkride-enrichment.json'

-- ====================================================================
-- Per-candidate enrichment
-- ====================================================================
local function enrichUnit(typeName)
    local ok, desc = pcall(function() return Unit.getDescByName(typeName) end)
    if not ok or not desc then return nil end

    local attrs = {}
    if type(desc.attributes) == 'table' then
        for k, v in pairs(desc.attributes) do
            if type(k) == 'string' and v == true then
                table.insert(attrs, k)
            end
        end
        table.sort(attrs)
    end

    return {
        typeName    = tostring(desc.typeName or typeName),
        displayName = desc.displayName and tostring(desc.displayName) or nil,
        category    = UNIT_CATEGORY_NAMES[desc.category] or tostring(desc.category),
        attributes  = attrs,
    }
end

local function enrichWeapon(typeName)
    local ok, desc = pcall(function() return Weapon.getDescByName(typeName) end)
    if not ok or not desc then return nil end

    local category = WEAPON_CATEGORY_NAMES[desc.category] or tostring(desc.category)
    if category == 'MISSILE' and desc.missileCategory then
        category = MISSILE_CATEGORY_NAMES[desc.missileCategory] or 'MISSILE'
    end

    return {
        typeName    = tostring(desc.typeName or typeName),
        displayName = desc.displayName and tostring(desc.displayName) or nil,
        category    = category,
        guidance    = GUIDANCE_NAMES[desc.guidance]
                      or (desc.guidance ~= nil and tostring(desc.guidance))
                      or 'NONE',
    }
end

local function runStaticEnrichment()
    enrichLog('Starting enrichment — ' .. tostring(#CANDIDATES) .. ' candidates')
    local unitCount, weaponCount, skipCount = 0, 0, 0

    for _, typeName in ipairs(CANDIDATES) do
        local unit = enrichUnit(typeName)
        if unit then
            table.insert(result.units, unit)
            unitCount = unitCount + 1
        else
            local weapon = enrichWeapon(typeName)
            if weapon then
                table.insert(result.weapons, weapon)
                weaponCount = weaponCount + 1
            else
                skipCount = skipCount + 1
            end
        end
    end

    table.sort(result.units,   function(a, b) return a.typeName < b.typeName end)
    table.sort(result.weapons, function(a, b) return a.typeName < b.typeName end)

    enrichLog(string.format(
        'Static enrichment done — units=%d weapons=%d skipped=%d',
        unitCount, weaponCount, skipCount))
end

-- Indexes existing airdrome names so we can deduplicate across multiple mission loads
local airdromeSeen = {}

local function enrichAirdromes(theater)
    local ok, airbases = pcall(function() return world.getAirbases() end)
    if not ok or not airbases then
        enrichLog('world.getAirbases() unavailable: ' .. tostring(airbases))
        return
    end

    local added = 0
    for _, ab in pairs(airbases) do
        local abOk, entry = pcall(function()
            local cat = ab:getCategory()
            return {
                name     = tostring(ab:getName()),
                id       = ab:getID(),
                category = AIRBASE_CATEGORY_NAMES[cat] or tostring(cat),
                theater  = theater,
            }
        end)
        if abOk and entry and entry.name ~= '' and not airdromeSeen[entry.name] then
            table.insert(result.airdromes, entry)
            airdromeSeen[entry.name] = true
            added = added + 1
        end
    end

    table.sort(result.airdromes, function(a, b) return a.name < b.name end)
    enrichLog(string.format(
        'Airdromes — added=%d total=%d theater=%s',
        added, #result.airdromes, theater))
end

local function writeOutput()
    local ok, encoded = pcall(encodeJson, result)
    if not ok then
        enrichLog('JSON encode failed: ' .. tostring(encoded))
        return
    end

    local f, err = io.open(outputPath, 'w')
    if not f then
        enrichLog('Cannot open output path: ' .. tostring(err))
        return
    end
    f:write(encoded)
    f:close()

    enrichLog('Output written → ' .. outputPath)
    enrichLog(string.format(
        'Summary — units=%d weapons=%d airdromes=%d',
        #result.units, #result.weapons, #result.airdromes))
end

-- ====================================================================
-- Hook callbacks
-- ====================================================================
local EnrichCallbacks = {}

local function getTheaterName()
    -- Try DCS terrain API (available in hooks, DCS 2.7+)
    local ok1, t1 = pcall(function()
        local terrain = require('terrain')
        return terrain.GetTerrainConfig('Ident')
    end)
    if ok1 and type(t1) == 'string' and t1 ~= '' then return t1 end

    -- Fallback: env.mission.theatre (mission scripting env; may not exist here)
    local ok2, t2 = pcall(function()
        return env and env.mission and env.mission.theatre
    end)
    if ok2 and type(t2) == 'string' and t2 ~= '' then return t2 end

    return 'unknown'
end

function EnrichCallbacks.onMissionLoadEnd()
    enrichLog('onMissionLoadEnd — collecting airdromes')

    local theaterName = getTheaterName()

    -- Track all theaters seen (accumulates across multiple mission loads)
    local alreadySeen = false
    for _, t in ipairs(result.meta.theaters) do
        if t == theaterName then alreadySeen = true; break end
    end
    if not alreadySeen then
        table.insert(result.meta.theaters, theaterName)
    end

    enrichAirdromes(theaterName)
    writeOutput()
end

DCS.setUserCallbacks(EnrichCallbacks)

-- Static enrichment runs immediately at hook load (no mission required)
local ok, err = pcall(runStaticEnrichment)
if not ok then
    enrichLog('Static enrichment failed: ' .. tostring(err))
else
    enrichLog('Static enrichment complete — load a mission to add airdrome data')
    -- Write partial results now so units/weapons are available even without a mission
    writeOutput()
end
