-- DCS-CheckrideEnricher.lua  (generated — do not edit by hand)
-- Generated by: node dev/tools/buildReferenceData.js generate
-- Candidates:   {{CANDIDATE_COUNT}}
--
-- USAGE:
--   1. Copy this file to:
--        <Saved Games>\DCS\Scripts\Hooks\DCS-CheckrideEnricher.lua
--   2. Stop the Checkride app (this hook replaces its callbacks).
--   3. Restart DCS, then load any mission (needed for airdrome data).
--   4. Output is written to:
--        <Saved Games>\DCS\checkride-enrichment.json
--   5. Back on the host machine, run:
--        node dev/tools/buildReferenceData.js process
--   6. Remove this hook file and restart DCS to restore normal operation.
--
-- Unit/weapon enrichment runs at simulation start (no mission needed).
-- Airdrome enumeration runs on mission load.  If you only need units/weapons,
-- the partial output written at sim-start is sufficient.

local lfs = require('lfs')
local log = require('log')

local function enrichLog(msg)
    log.write('CheckrideEnricher', log.INFO, tostring(msg))
end

-- ====================================================================
-- JSON encoder (mirrors DCS-CheckrideMission.lua style)
-- ====================================================================
local function jsonEscape(str)
    str = tostring(str)
    str = str:gsub('\\', '\\\\')
    str = str:gsub('"',  '\\"')
    str = str:gsub('\n', '\\n')
    str = str:gsub('\r', '\\r')
    str = str:gsub('\t', '\\t')
    return str
end

local function isSeqTable(t)
    if type(t) ~= 'table' then return false end
    local n = 0
    for k in pairs(t) do
        if type(k) ~= 'number' then return false end
        n = n + 1
    end
    for i = 1, n do if t[i] == nil then return false end end
    return true
end

local function encodeJson(val, depth)
    depth = depth or 0
    if depth > 20 then return '"<depth_limit>"' end
    local t = type(val)
    if t == 'nil'     then return 'null' end
    if t == 'boolean' then return tostring(val) end
    if t == 'number'  then
        if val ~= val or val >= math.huge or val <= -math.huge then return 'null' end
        return tostring(val)
    end
    if t == 'string' then return '"' .. jsonEscape(val) .. '"' end
    if t == 'table' then
        if isSeqTable(val) then
            local parts = {}
            for i, v in ipairs(val) do parts[i] = encodeJson(v, depth + 1) end
            return '[' .. table.concat(parts, ',') .. ']'
        end
        local parts = {}
        for k, v in pairs(val) do
            if type(k) == 'string' then
                table.insert(parts, '"' .. jsonEscape(k) .. '":' .. encodeJson(v, depth + 1))
            end
        end
        return '{' .. table.concat(parts, ',') .. '}'
    end
    return 'null'
end

-- ====================================================================
-- Candidates (auto-generated — {{CANDIDATE_COUNT}} total)
-- ====================================================================
local CANDIDATES = {
{{CANDIDATES}}
}

-- ====================================================================
-- Enum mappings — must stay in sync with DCS-CheckrideMission.lua
-- ====================================================================
local GUIDANCE_NAMES = {
    [0] = 'NONE',
    [4] = 'RADAR_ACTIVE',
    [5] = 'RADAR_SEMI_ACTIVE',
    [6] = 'RADAR_PASSIVE',
    [7] = 'IR',
    [8] = 'LASER',
    [9] = 'TV',
}

local WEAPON_CATEGORY_NAMES = {
    [0] = 'SHELL',
    [1] = 'MISSILE',
    [2] = 'ROCKET',
    [3] = 'BOMB',
    [4] = 'TORPEDO',
}

local MISSILE_CATEGORY_NAMES = {
    [1] = 'AAM',
    [2] = 'SAM',
    [3] = 'BM',
    [4] = 'ANTI_SHIP',
    [5] = 'ARM',
    [6] = 'OTHER',
}

-- Numeric constants so we don't depend on Unit.Category being defined at hook load time
local UNIT_CATEGORY_NAMES = {
    [0] = 'AIRPLANE',
    [1] = 'HELICOPTER',
    [2] = 'GROUND_UNIT',
    [3] = 'SHIP',
    [4] = 'STRUCTURE',
}

local AIRBASE_CATEGORY_NAMES = {
    [0] = 'AIRDROME',
    [1] = 'HELIPAD',
    [2] = 'SHIP',
}

-- ====================================================================
-- Accumulated result
-- ====================================================================
local result = {
    units     = {},
    weapons   = {},
    airdromes = {},
    meta = {
        generatedAt       = os.date('!%Y-%m-%dT%H:%M:%SZ'),
        candidatesScanned = {{CANDIDATE_COUNT}},
        theaters          = {},
    },
}

local outputPath = lfs.writedir() .. 'checkride-enrichment.json'

-- ====================================================================
-- Per-candidate enrichment
-- ====================================================================
local function enrichUnit(typeName)
    local ok, desc = pcall(function() return Unit.getDescByName(typeName) end)
    if not ok or not desc then return nil end

    local attrs = {}
    if type(desc.attributes) == 'table' then
        for k, v in pairs(desc.attributes) do
            if type(k) == 'string' and v == true then
                table.insert(attrs, k)
            end
        end
        table.sort(attrs)
    end

    return {
        typeName    = tostring(desc.typeName or typeName),
        displayName = desc.displayName and tostring(desc.displayName) or nil,
        category    = UNIT_CATEGORY_NAMES[desc.category] or tostring(desc.category),
        attributes  = attrs,
    }
end

local function enrichWeapon(typeName)
    local ok, desc = pcall(function() return Weapon.getDescByName(typeName) end)
    if not ok or not desc then return nil end

    local category = WEAPON_CATEGORY_NAMES[desc.category] or tostring(desc.category)
    if category == 'MISSILE' and desc.missileCategory then
        category = MISSILE_CATEGORY_NAMES[desc.missileCategory] or 'MISSILE'
    end

    return {
        typeName    = tostring(desc.typeName or typeName),
        displayName = desc.displayName and tostring(desc.displayName) or nil,
        category    = category,
        guidance    = GUIDANCE_NAMES[desc.guidance]
                      or (desc.guidance ~= nil and tostring(desc.guidance))
                      or 'NONE',
    }
end

local function runStaticEnrichment()
    enrichLog('Starting enrichment — ' .. tostring(#CANDIDATES) .. ' candidates')
    local unitCount, weaponCount, skipCount = 0, 0, 0

    for _, typeName in ipairs(CANDIDATES) do
        local unit = enrichUnit(typeName)
        if unit then
            table.insert(result.units, unit)
            unitCount = unitCount + 1
        else
            local weapon = enrichWeapon(typeName)
            if weapon then
                table.insert(result.weapons, weapon)
                weaponCount = weaponCount + 1
            else
                skipCount = skipCount + 1
            end
        end
    end

    table.sort(result.units,   function(a, b) return a.typeName < b.typeName end)
    table.sort(result.weapons, function(a, b) return a.typeName < b.typeName end)

    enrichLog(string.format(
        'Static enrichment done — units=%d weapons=%d skipped=%d',
        unitCount, weaponCount, skipCount))
end

-- Indexes existing airdrome names so we can deduplicate across multiple mission loads
local airdromeSeen = {}

local function enrichAirdromes(theater)
    local ok, airbases = pcall(function() return world.getAirbases() end)
    if not ok or not airbases then
        enrichLog('world.getAirbases() unavailable: ' .. tostring(airbases))
        return
    end

    local added = 0
    for _, ab in pairs(airbases) do
        local abOk, entry = pcall(function()
            local cat = ab:getCategory()
            return {
                name     = tostring(ab:getName()),
                id       = ab:getID(),
                category = AIRBASE_CATEGORY_NAMES[cat] or tostring(cat),
                theater  = theater,
            }
        end)
        if abOk and entry and entry.name ~= '' and not airdromeSeen[entry.name] then
            table.insert(result.airdromes, entry)
            airdromeSeen[entry.name] = true
            added = added + 1
        end
    end

    table.sort(result.airdromes, function(a, b) return a.name < b.name end)
    enrichLog(string.format(
        'Airdromes — added=%d total=%d theater=%s',
        added, #result.airdromes, theater))
end

local function writeOutput()
    local ok, encoded = pcall(encodeJson, result)
    if not ok then
        enrichLog('JSON encode failed: ' .. tostring(encoded))
        return
    end

    local f, err = io.open(outputPath, 'w')
    if not f then
        enrichLog('Cannot open output path: ' .. tostring(err))
        return
    end
    f:write(encoded)
    f:close()

    enrichLog('Output written → ' .. outputPath)
    enrichLog(string.format(
        'Summary — units=%d weapons=%d airdromes=%d',
        #result.units, #result.weapons, #result.airdromes))
end

-- ====================================================================
-- Hook callbacks
-- ====================================================================
local EnrichCallbacks = {}

local function getTheaterName()
    -- Try DCS terrain API (available in hooks, DCS 2.7+)
    local ok1, t1 = pcall(function()
        local terrain = require('terrain')
        return terrain.GetTerrainConfig('Ident')
    end)
    if ok1 and type(t1) == 'string' and t1 ~= '' then return t1 end

    -- Fallback: env.mission.theatre (mission scripting env; may not exist here)
    local ok2, t2 = pcall(function()
        return env and env.mission and env.mission.theatre
    end)
    if ok2 and type(t2) == 'string' and t2 ~= '' then return t2 end

    return 'unknown'
end

function EnrichCallbacks.onMissionLoadEnd()
    enrichLog('onMissionLoadEnd — collecting airdromes')

    local theaterName = getTheaterName()

    -- Track all theaters seen (accumulates across multiple mission loads)
    local alreadySeen = false
    for _, t in ipairs(result.meta.theaters) do
        if t == theaterName then alreadySeen = true; break end
    end
    if not alreadySeen then
        table.insert(result.meta.theaters, theaterName)
    end

    enrichAirdromes(theaterName)
    writeOutput()
end

DCS.setUserCallbacks(EnrichCallbacks)

-- Static enrichment runs immediately at hook load (no mission required)
local ok, err = pcall(runStaticEnrichment)
if not ok then
    enrichLog('Static enrichment failed: ' .. tostring(err))
else
    enrichLog('Static enrichment complete — load a mission to add airdrome data')
    -- Write partial results now so units/weapons are available even without a mission
    writeOutput()
end
