-- checkride-enricher-mission.lua  (generated — do not edit by hand)
-- Generated by: node dev/tools/buildReferenceData.js generate
-- Candidates:   {{CANDIDATE_COUNT}}
--
-- This file runs inside the DCS Mission Scripting Environment (MSE), injected
-- by DCS-CheckrideEnricher.lua via net.dostring_in('server', dofile(path)).
-- Unit.getDescByName / Weapon.getDescByName / world.getAirbases() are all
-- available here.  It writes output to:
--   <Saved Games>\DCS\checkride-enrichment.json

local lfs = require('lfs')

local function enrichLog(msg)
    env.info('[CheckrideEnricher] ' .. tostring(msg))
end

-- ====================================================================
-- JSON encoder
-- ====================================================================
local function jsonEscape(str)
    str = tostring(str)
    str = str:gsub('\\', '\\\\')
    str = str:gsub('"',  '\\"')
    str = str:gsub('\n', '\\n')
    str = str:gsub('\r', '\\r')
    str = str:gsub('\t', '\\t')
    return str
end

local function isSeqTable(t)
    if type(t) ~= 'table' then return false end
    local n = 0
    for k in pairs(t) do
        if type(k) ~= 'number' then return false end
        n = n + 1
    end
    for i = 1, n do if t[i] == nil then return false end end
    return true
end

local function encodeJson(val, depth)
    depth = depth or 0
    if depth > 20 then return '"<depth_limit>"' end
    local t = type(val)
    if t == 'nil'     then return 'null' end
    if t == 'boolean' then return tostring(val) end
    if t == 'number'  then
        if val ~= val or val >= math.huge or val <= -math.huge then return 'null' end
        return tostring(val)
    end
    if t == 'string' then return '"' .. jsonEscape(val) .. '"' end
    if t == 'table' then
        if isSeqTable(val) then
            local parts = {}
            for i, v in ipairs(val) do parts[i] = encodeJson(v, depth + 1) end
            return '[' .. table.concat(parts, ',') .. ']'
        end
        local parts = {}
        for k, v in pairs(val) do
            if type(k) == 'string' then
                table.insert(parts, '"' .. jsonEscape(k) .. '":' .. encodeJson(v, depth + 1))
            end
        end
        return '{' .. table.concat(parts, ',') .. '}'
    end
    return 'null'
end

-- ====================================================================
-- Candidates (auto-generated — {{CANDIDATE_COUNT}} total)
-- ====================================================================
local CANDIDATES = {
{{CANDIDATES}}
}

-- ====================================================================
-- Enum mappings — kept in sync with DCS-CheckrideMission.lua
-- ====================================================================
local GUIDANCE_NAMES = {
    [0] = 'NONE',
    [4] = 'RADAR_ACTIVE',
    [5] = 'RADAR_SEMI_ACTIVE',
    [6] = 'RADAR_PASSIVE',
    [7] = 'IR',
    [8] = 'LASER',
    [9] = 'TV',
}

local WEAPON_CATEGORY_NAMES = {
    [0] = 'SHELL',
    [1] = 'MISSILE',
    [2] = 'ROCKET',
    [3] = 'BOMB',
    [4] = 'TORPEDO',
}

local MISSILE_CATEGORY_NAMES = {
    [1] = 'AAM',
    [2] = 'SAM',
    [3] = 'BM',
    [4] = 'ANTI_SHIP',
    [5] = 'ARM',
    [6] = 'OTHER',
}

local UNIT_CATEGORY_NAMES = {
    [0] = 'AIRPLANE',
    [1] = 'HELICOPTER',
    [2] = 'GROUND_UNIT',
    [3] = 'SHIP',
    [4] = 'STRUCTURE',
}

local AIRBASE_CATEGORY_NAMES = {
    [0] = 'AIRDROME',
    [1] = 'HELIPAD',
    [2] = 'SHIP',
}

-- ====================================================================
-- Result accumulator
-- ====================================================================
local theaterName = 'unknown'
if env and env.mission and type(env.mission.theatre) == 'string' and env.mission.theatre ~= '' then
    theaterName = env.mission.theatre
end

local result = {
    units     = {},
    weapons   = {},
    airdromes = {},
    meta = {
        generatedAt       = os.date('!%Y-%m-%dT%H:%M:%SZ'),
        candidatesScanned = {{CANDIDATE_COUNT}},
        theater           = theaterName,
    },
}

local outputPath = lfs.writedir() .. 'checkride-enrichment.json'

-- ====================================================================
-- Per-candidate enrichment
-- ====================================================================
local function enrichUnit(typeName)
    local ok, desc = pcall(function() return Unit.getDescByName(typeName) end)
    if not ok or not desc then return nil end

    local attrs = {}
    if type(desc.attributes) == 'table' then
        for k, v in pairs(desc.attributes) do
            if type(k) == 'string' and v == true then
                table.insert(attrs, k)
            end
        end
        table.sort(attrs)
    end

    return {
        typeName    = tostring(desc.typeName or typeName),
        displayName = desc.displayName and tostring(desc.displayName) or nil,
        category    = UNIT_CATEGORY_NAMES[desc.category] or tostring(desc.category),
        attributes  = attrs,
    }
end

local function enrichWeapon(typeName)
    local ok, desc = pcall(function() return Weapon.getDescByName(typeName) end)
    if not ok or not desc then return nil end

    local category = WEAPON_CATEGORY_NAMES[desc.category] or tostring(desc.category)
    if category == 'MISSILE' and desc.missileCategory then
        category = MISSILE_CATEGORY_NAMES[desc.missileCategory] or 'MISSILE'
    end

    return {
        typeName    = tostring(desc.typeName or typeName),
        displayName = desc.displayName and tostring(desc.displayName) or nil,
        category    = category,
        guidance    = GUIDANCE_NAMES[desc.guidance]
                      or (desc.guidance ~= nil and tostring(desc.guidance))
                      or 'NONE',
    }
end

enrichLog('Starting enrichment — ' .. tostring(#CANDIDATES) .. ' candidates')
local unitCount, weaponCount, skipCount = 0, 0, 0

for _, typeName in ipairs(CANDIDATES) do
    -- Try Weapon first: Unit.getDescByName also returns entries for ammo/shell type names
    -- (categorising them as STRUCTURE), so checking Weapon first avoids misclassification.
    local weapon = enrichWeapon(typeName)
    if weapon then
        table.insert(result.weapons, weapon)
        weaponCount = weaponCount + 1
    else
        local unit = enrichUnit(typeName)
        if unit then
            table.insert(result.units, unit)
            unitCount = unitCount + 1
        else
            skipCount = skipCount + 1
        end
    end
end

table.sort(result.units,   function(a, b) return a.typeName < b.typeName end)
table.sort(result.weapons, function(a, b) return a.typeName < b.typeName end)

enrichLog(string.format(
    'Enrichment done — units=%d weapons=%d skipped=%d',
    unitCount, weaponCount, skipCount))

-- ====================================================================
-- Airdromes
-- ====================================================================
local abOk, airbases = pcall(function() return world.getAirbases() end)
if abOk and airbases then
    for _, ab in pairs(airbases) do
        local entryOk, entry = pcall(function()
            local cat = ab:getCategory()
            return {
                name     = tostring(ab:getName()),
                id       = ab:getID(),
                category = AIRBASE_CATEGORY_NAMES[cat] or tostring(cat),
                theater  = theaterName,
            }
        end)
        if entryOk and entry and entry.name ~= '' then
            table.insert(result.airdromes, entry)
        end
    end
    table.sort(result.airdromes, function(a, b) return a.name < b.name end)
    enrichLog(string.format('Airdromes — count=%d theater=%s', #result.airdromes, theaterName))
else
    enrichLog('world.getAirbases() unavailable: ' .. tostring(airbases))
end

-- ====================================================================
-- Write output
-- ====================================================================
local encodeOk, encoded = pcall(encodeJson, result)
if not encodeOk then
    enrichLog('JSON encode failed: ' .. tostring(encoded))
    return 'FAILED: JSON encode — ' .. tostring(encoded)
end

local f, err = io.open(outputPath, 'w')
if not f then
    enrichLog('Cannot open output path: ' .. tostring(err))
    return 'FAILED: io.open — ' .. tostring(err)
end
f:write(encoded)
f:close()

enrichLog('Output written → ' .. outputPath)
enrichLog(string.format(
    'Summary — units=%d weapons=%d airdromes=%d',
    #result.units, #result.weapons, #result.airdromes))

return string.format('OK units=%d weapons=%d airdromes=%d', #result.units, #result.weapons, #result.airdromes)
